package cinema.db.response

enum class Status {
    OK,
    SESSION_HAS_STARTED,
    SESSION_DOES_NOT_EXIST,
    SESSIONS_OVERLAP,
    TICKET_DOES_NOT_EXIST,
    TICKET_IS_ALREADY_CONFIRMED,
    FILM_DOES_NOT_EXIST,
    SEAT_IS_OCCUPIED,
}